services:
  frontend:
    image: node:22.16-alpine
    working_dir: "/app"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      BASE_API_URL: ${BASE_API_URL:-/}
    command: "sh -c 'npm install && npm run dev'"

  backend:
    image: node:22.16-alpine
    working_dir: "/app/backend"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/backend/node_modules
    env_file:
      - .env
    command: "sh -c 'npm install && node server.js'"

  nginx:
    environment:
      - NGINX_PORT=80
    user: root
    ports:
      - "8080:80"